### ISSUE TITLE
Logger API `Error(...)` method

### ISSUE THREAD

**Issue by jamesrom** [anz-bank/pkg#15]
A convenience function to help with error handling could be useful.

```go
if err != nil {
    log.From(ctx).Error("Couldn't foo", err)
    return err
}
```
Should produce something like

```sh
msg="Couldn't foo" error_message="connection timed out"
```

**Comment by anzdaddy** [comment]
Seems pretty useful. Let's add it. Semantically, I think it should be just a variant of `Info`, not a different "level".
